Wiki boost
cristicretu/arcboost-marketplace pull request #5
Opened 2022-10-07 19:55 UTC by khushmeeet

## Describe your Arc Boost
Simplify Wikipedia page for reading. Removes sidebar and increases font size.

## Checklist before requesting a merge

- [x] I have copied the extension zip file into the public/extensions folder

- [x] I have created a new JSON file in the data/manifest folder, with the extensions' id
- [x] I have filled all the blank lines in the JSON file
- [x] I have tested it locally
- [x] I have uploaded a picture here, then used the `user-images.githubusercontent...` URL inside the JSON file

> Upload your preview picture here
![SCR-20221007-lfa](https://user-images.githubusercontent.com/8711912/194642763-cb7d8e66-83a4-4513-a387-39ceca439ce6.jpeg)

2022-10-08 06:21 UTC, cristicretu commented on .vscode/settings.json
> +  "workbench.preferredDarkColorTheme": "Vitesse Dark"
```suggestion
  },
```

2022-10-08 06:26 UTC, cristicretu requested changes
I suggest adding `!important` for every rule, otherwise not all the will styles work. (or at least they didn't work from the start for me)
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/45521157/194692772-6c894f5f-a44e-402a-9345-160e6c4bc479.png">

2022-10-08 06:26 UTC, cristicretu commented on .vscode/settings.json
> +  "workbench.preferredDarkColorTheme": "Vitesse Dark"
```suggestion
  }
```

2022-10-08 21:12 UTC, khushmeeet commented on .vscode/settings.json
> +  "workbench.preferredDarkColorTheme": "Vitesse Dark"
I updated the files as requested.

2022-10-09 04:15 UTC, cristicretu commented
Great job! Cool boost and thanks for the first contribution 🥳

2022-10-09 04:16 UTC, cristicretu approved these changes

2022-10-09 04:16 UTC, merged